server:
  servlet:
    context-path: /bakery-inventory-service/api
  port: 8082

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

db:
  host: ${DB_HOST}
  port: ${DB_PORT:5433}
  name: ${DB_NAME}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}

app:
  clients:
    bakery-user-service:
      url: ${BAKERY_USER_SERVICE_URL}

spring:
  datasource:
    url: jdbc:postgresql://${db.host}:${db.port}/${db.name}
    username: ${db.username}
    password: ${db.password}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
        format_sql: true

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 250MB

flyway:
  enabled: true
  baseline-on-migrate: true
  schemas: public
  url: jdbc:postgresql://${db.host}:${db.port}/${db.name}
  userEntity: ${db.username}
  password: ${db.password}

allowed:
  urls: ${ALLOWED_ORIGIN:https://your-frontend-domain.com}