server:
  servlet:
    context-path: /bakery-inventory-service/api
  port: 8082

db:
  host: localhost
  port: 5433
  name: bakery-inventory-db
  username: admin
  password: admin

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

app:
  clients:
    bakery-user-service:
      url: http://localhost:8081/bakery-user-service/api

spring:
  datasource:
    url: jdbc:postgresql://${db.host}:${db.port}/${db.name}
    username: ${db.username}
    password: ${db.password}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
        format_sql: true

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 250MB

flyway:
  enabled: true
  baseline-on-migrate: true
  schemas: public
  url: jdbc:postgresql://${db.host}:${db.port}/${db.name}
  userEntity: ${db.username}
  password: ${db.password}

# APPLICATION
allowed:
  urls: http://localhost:3000

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace